name: flutter_live_data_example
version: 2.1.1
homepage: https://github.com/tanapoj/flutter_live_data

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: