name: flutter_live_data
description: LiveData for Flutter, Stream warpper make easy control and robust feature.
version: 2.2.5
homepage: https://github.com/tanapoj/flutter_live_data

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: