name: flutter_live_data
description: LiveData for Flutter, Stream warpper make easy control and robust feature.
version: 2.2.5
homepage: https://github.com/tanapoj/flutter_live_data

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: